project:
  type: book
  output-dir: docs

book:
  title: "GF0604 Procesamiento de datos geográficos 2024-I"
  author: "Manuel Vargas"
  date: "2024-03-03"
  chapters:
    - index.qmd
    - programa_curso.qmd
    - part: parte-i-introduccion-programacion_computadoras_ciencia_datos.qmd

bibliography: referencias.bib

format:
  html:
    lang: es
    theme: cosmo