# Bienvenida {.unnumbered}
Este es un curso introductorio a la programación de computadoras y al procesamiento de datos geográficos mediante el lenguaje de programación [R](https://www.r-project.org/). También se estudian herramientas para facilitar la reproducibilidad de los procedimientos y la comunicación de las soluciones a través de Internet y otros medios. Se imparte en la [Escuela de Geografía](https://www.geografia.fcs.ucr.ac.cr/) de la [Universidad de Costa Rica](https://www.ucr.ac.cr/).

El enfoque del curso es teórico-práctico, con lecciones teóricas combinadas con ejercicios de programación en los cuales los estudiantes aplican en diversos escenarios de procesamiento de datos los conocimientos y habilidades aprendidas. No se requiere de experiencia previa en programación de computadoras. Es recomendable contar con conocimentos básicos de datos geoespaciales y sistemas de información geográfica.

Tanto las lecciones teóricas como las prácticas se imparten de manera presencial, con apoyo de medios virtuales. Los contenidos del curso y los recursos relacionados se comparten en el sitio web [https://gf0604-procesamientodatosgeograficos.github.io/2024-i/](https://gf0604-procesamientodatosgeograficos.github.io/2024-i/) y en la plataforma [Mediación Virtual](https://mediacionvirtual.ucr.ac.cr/) de la Universidad de Costa Rica. 
